### PR TITLE
robot-name: Add test versioning

### PR DESCRIPTION
**Pull request by tleen**
See #470

### CODE REVIEW

**Comment by robphoenix** [comment]
Does this need to be considered here also? https://github.com/exercism/xgo/pull/536#issuecomment-281337014

**Comment by tleen** [comment]
Yes I think so. Wasn't quite sure what to do with the testing stuff in bonus, so didn't. What was the final consensus, leave it or strip it?

**Comment by robphoenix** [comment]
strip it, so the test version info is only in the initial/main test files and not in any extra/bonus files.

**Comment by robphoenix** [comment]
:+1: LGTM. Be good to squash the commits for merging.

**Pull request merged**
