### PR TITLE
Delete the SHA1 for retired testVersions

### PR DESCRIPTION
**Pull request by kytrinyx**
These were a bit confusing, and it seems easier to simply git log -p within the file
we're interested in.

### CODE REVIEW

**Comment by petertseng** [comment]
wholehearted support.

I believe this would be a good time to delete the comments in `passio_test.go` about `testVersion` (I *knew* I saw those somewhere, but couldn't find them until I grepped  for `testVersion` just now to make sure nothing was missed

**Comment by kytrinyx** [comment]
Oooh, yepp. Let me do that in this PR.

**Comment by kytrinyx** [comment]
Updated.

**Comment by petertseng** [comment]
Seems good. I hope you don't mind if I just merge that.

**Comment by kytrinyx** [comment]
Nah, that's great, thanks.

**Pull request merged**
