### PR TITLE
Add ignore pattern

### PR DESCRIPTION
**Pull request by robphoenix**
see #621
see also exercism/trackler#33

This adds a repo specific ignore pattern. The default pattern
`/example/` excludes example test files, such as
`example_helloworld_test.go`, which should not be ignored.

This pattern ignores a filename that contains the word `example`, unless
the word `example` is followed by the word `test`, with any number of
characters inbetween.

For instance, these files will be ignored:

`example.go`
`example_slice.go` (from the `custom-set` exercise)

however these files will not be ignored:

`example_test.go`
`example_clock_test.go`
`example_helloworld_test.go`

### CODE REVIEW

**Comment by robphoenix** [comment]
@Insti I'd appreciate if you could give a quick look over this, just to make sure I've not misunderstood your intentions. Thanks.

**Comment by robphoenix** [comment]
closes #621

**Comment by Insti** [comment]
> Ideally the track should put everything it wants ignored into the .meta directory and set ignore_pattern to ""

This is more a general concept rather than a specific criticism of this PR.
(And I need to check what happens if you set the ignore_pattern to "")

**Comment by petertseng** [comment]
> (And I need to check what happens if you set the ignore_pattern to "")

Incomplete piece of the puzzle:

```
ruby -e 'puts Regexp.new("").match?("arbitrary_path")'
true
```

So if both are true:

* a track sets ignore_pattern to ""
* there is no other special handling of ""

then all paths are ignored.

**Comment by kytrinyx** [comment]
> then all paths are ignored.

Yeah, my assumption was that if you don't want to ignore paths, your ignore_path is not present (or is explicitly null) and you get the default. We can probably safely assume that "" means that they want the default, because ignoring all the paths seems like a pretty silly approach...

**Comment by kytrinyx** [comment]
> We can probably safely assume

I don't actually know whether to explicitly change trackler to protect tracks from defining `//` as the ignore path.

**Comment by robphoenix** [comment]
> Ideally the track should put everything it wants ignored into the .meta directory and set ignore_pattern to ""

Yes, I agree. I haven't done this as we would then have to move the `example.go` file out of the `.meta` dir for it to be picked up by the tests. Though, that shouldn't happen a lot, only during development, not for a user, and we have to either remove or comment out any repeated code in a stub file if there is one. 

@petertseng I'd like to get your opinion on whether we should add this ignore pattern or move the `example.go` file into `.meta`. Essentially, is this PR good to merge?

**Comment by Insti** [comment]
> I haven't done this as we would then have to move the example.go file out of the .meta dir for it to be picked up by the tests. 

Or update the tests to look at `.meta/solutions/example.go` for the example solution.

**Comment by robphoenix** [comment]
Yeah, looking at the test-without-stubs file that Travis uses, it may be less of an issue than I initially thought.

**Comment by petertseng** [comment]
>  Will mean contributors to this track can no longer `go test` to test the example

Yeah I know some *other* tracks don't have this property either, but might as while keep it while we can. If we need to give it up, need to allow `test_without_stubs` to take a single exercise instead of all of them; wouldn't want to have to wait for all the tests to run if only testing one exercise.l

**Pull request merged**
