### PR TITLE
Remove stutter from API of meetup

### PR DESCRIPTION
**Pull request by kytrinyx**

### CODE REVIEW

**Comment by petertseng** [comment]
Yup seems good. One small question - the git shas in the old version log: Should that be "first commit that does NOT comply with this version" or "last commit that DOES comply?"

I only ask because in this PR you've done the former, whereas IIRC I did the latter in my previous PRs. I guess there isn't a hard rule about it but I'll ask in case anyone cares deeply.

**Comment by kytrinyx** [comment]
> One small question - the git shas in the old version log

I have no idea!

> Is that log even useful?

I'm not so sure. I think `git log -p` on the file would be the better way of go.
I think I'll just go through and delete these.

**Comment by petertseng** [comment]
I would be in agreement.

In the meantime, :+1:  on this PR

**Comment by kytrinyx** [comment]
Sweet. Thanks!

**Pull request merged**
