### PR TITLE
[Do Not Merge] acronym: replace test file with example test

### PR DESCRIPTION
**Pull request by robphoenix**
see #420

### CODE REVIEW

**Comment by robphoenix** [comment]
Ok, so I'm actually presenting this as a case against replacing the standard test files with example tests. Why? Well I think they present a degraded feedback loop when errors occur and this is not the intended use for them. If a user get's something wrong the error returned will be something like this:

```
--- FAIL: ExampleAbbreviate (0.00s)
got:
PNG
ROR
HTML
FIFO
PHP
GIMP
CMOS
want:
WRONG
PNG
ROR
HTML
FIFO
PHP
GIMP
CMOS
FAIL
exit status 1
FAIL	github.com/robphoenix/xgo/exercises/acronym	0.003s
```

Which can become a confusing wall of text in all but examples with a small output, rather than a helpful message. In standard tests we have a lot more control over how we test the code and report back on any errors that occur. Even in small exercises like this I don't think having only example tests is beneficial. If we want to introduce users to this other way of verifying code I believe it would be better done as an addition to a standard test file. 
I suggest we close #420 and ensure we properly document the potential for using example tests as a helpful addition in exercises where there may be confusion, as in `clock`.

**Comment by tleen** [comment]
I think @robphoenix is right here. The more I work with Examples the more it seems like we would be overloading their purpose to use them as actual tests against the solutions. Ideally the tests fail early and fail informatively. Example tests fail monolithically and generically.

**Comment by petertseng** [comment]
Yeah, not really seeing their usefulness here. It would kind of make sense if there were one line of output per test, but in that case I don't also see the benefit over a table-based test.

**Comment by robphoenix** [comment]
OK, it seems there's a general agreement that Example tests are not here to replace table-based tests, rather their usefulness is in clarifying how an exercise's API works. Thanks everyone for chipping in on this, I'll ensure the README is clear on this. :+1:

**Pull request closed without merging**
