### PR TITLE
config.json: add info for queen-attack

### PR DESCRIPTION
**Pull request by robphoenix**
see #345
change difficulty
add topics

### CODE REVIEW

**Comment by robphoenix** [comment]
I'm a little uncertain about these topics, any thoughts?

**Comment by tleen** [comment]
Why booleans? Is is because the result is a true/false? 

One keyword that may be appropriate is something along the lines of "matrix" or "multi-dimensional (array)" since that is the conceptual visualization?

**Comment by tleen** [comment]
Perhaps "Errors" would be a good topic since this (and hamming) is an early exercise requiring errors as part of the function sig.

**Comment by robphoenix** [comment]
I like both these suggestions, I'll add them in. :+1:

**Pull request merged**
