### PR TITLE
Add connect exercise

### PR DESCRIPTION
**Pull request by pminten**
Would appreciate some critique, I've been out of Go for a few years.

One thing I'm particularly unsure about is what's more idiomatic, the current

```go
coords := make([]coord, b.height)
for i := 0; i < b.height; i++ {
	coords[i] = coord{x: 0, y: i}
}
```

or

```go
coords := make([]coord, 0, b.height)
for i := 0; i < b.height; i++ {
	coords = append(coords, coord{x: 0, y: i})
}
```

### CODE REVIEW

**Comment by soniakeys** [comment]
Hello Peter,
For that specific question, I like the first version better.  It's simpler and I think simple is idiomatic and more readable.

**Comment by kytrinyx** [comment]
Yes, I also like the first version better.

Would you add "connect" to the config.json, please?

**Comment by pminten** [comment]
@kytrinyx Done.

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
