### PR TITLE
anagram: Fix test case for case sensitivity

### PR DESCRIPTION
**Pull request by ferhatelmas**
Response should return actual input.

### CODE REVIEW

**Comment by kytrinyx** [comment]
`tc` was probably test case. I would probably go with `tests` and `test` now rather than `testCases` and `tc`

**Comment by ferhatelmas** [comment]
I had meaned `test candidate` with `tc` since `c` was used for `candidate`. Do you want me to change it to `lc` or `test` or anything else ?

**Comment by petertseng** [comment]
I'm good with this as-is. I suppose it isn't a test case since it's in an example file

**Comment by ferhatelmas** [comment]
I agree.

**Pull request merged**
