### PR TITLE
minesweeper: Ensure test versioning consistency with other exercises

### PR DESCRIPTION
**Pull request by tleen**
* Moved TestTestFunction to top of test functions
* Errorf -> Fatalf

See #470

### CODE REVIEW

**Comment by ferhatelmas** [comment]
What about commit message ?

**Comment by tleen** [comment]
Yeah jeez what happened there.

**Comment by ferhatelmas** [comment]
@tleen Thanks :heart:

**Comment by tleen** [comment]
Thank you, i'm embarrassed I missed that!

**Comment by ferhatelmas** [comment]
@tleen Really you shouldn't. It happens all the time to all of us :wink:

**Pull request merged**
