### PR TITLE
Move exercises to subdirectory. Fixes #223

### LINKED ISSUE #223: Move exercises to subdirectory
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

### PR DESCRIPTION
**Pull request by kytrinyx**

### CODE REVIEW

**Comment by petertseng** [comment]
Looks good, though I guess you could let someone look at it again after rebasing. All I really did here though was see that all the exercise dirs got moved and no dirs got moved that shouldn't have. I'm trusting y'all on the API allowing `/exercises/` bit

**Comment by kytrinyx** [comment]
Rebased.

**Comment by petertseng** [comment]
Seems good to me. I think the build failure is a transient one? I don't know how to get travis to retry though. (Usually I just make an inconsequential change in my commit message and push again, that gets a retry going)

**Comment by kytrinyx** [comment]
There's a 'restart build' button in travis that you should have access to (upper right corner).

retry

**Comment by kytrinyx** [comment]
I kicked it off again. We'll see.

**Comment by petertseng** [comment]
Confirmed I see that button. Guess the light coloring means I don't see it unless I know where to look for it. OK then.

**Comment by kytrinyx** [comment]
Now it's a different one that broke. what the heck?

**Comment by kytrinyx** [comment]
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

So it's stalling. It might just be graemlins in the travis CI system.

**Comment by kytrinyx** [comment]
And green. OK, I think we're good to go.

**Pull request merged**
