### PR TITLE
test-without-stubs,exercises: Typo fixes

### PR DESCRIPTION
**Pull request by ferhatelmas**
- used https://github.com/client9/misspell

### CODE REVIEW

**Comment by ferhatelmas** [comment]
We might want to add this into CI but not sure because we can get false positives. What do you think ?

**Comment by tleen** [comment]
If changes would be rejected because of false positives it sort of has to be a no? We shouldn't have things fail if they are correct. I do think running this process occasionally would help tighten things up.

**Comment by ferhatelmas** [comment]
I agree.

**Comment by robphoenix** [comment]
Is it worth adding a note somewhere, perhaps the README, about this, so it doesn't get lost here?

**Comment by tleen** [comment]
May be worth pointing out the tool, but effectively it will be up to us to periodically check by using it.

**Pull request merged**
