### PR TITLE
replace 'problems' key with 'exercises' in config.json

### PR DESCRIPTION
**Pull request by cgrayson**
see #345

### CODE REVIEW

**Comment by petertseng** [comment]
Can I get a confirm that it is safe to **delete** the problems key?

Yes, it appears I can get it. https://github.com/exercism/x-api/pull/137 has made it happen. Good. One last check before merge (that the order is the same.

**Comment by petertseng** [comment]
Good, empty output from `diff -u <(jq '.["problems"]' < config.json) <(jq '.["exercises"] | map(.["slug"])' < newconfig.json)`

One last question: Should we put the `slug` key before the `difficulty` key?

**Comment by cgrayson** [comment]
I listed the attributes alphabetically, as I'm used to doing in JSON, but if you prefer `slug` first, happy to change it.

**Comment by petertseng** [comment]
I really wished I could point to an example of how it should be done, but my hope was dashed! Because #345 has it BOTH ways ("hello-world" is slug first, and then "anagram" and "forth" are alphabetical!)

My *instinct* was slug first since it is "the most important", but now I have no ground to stand on! @kytrinyx does this matter to you? If not I'll just take it.

**Comment by petertseng** [comment]
We could just take it now and defer the decision. If we want to change it, we can change it when we make the difficulty values non-1, since all the lines will change anyway. Except the ones that stay 1.

**Comment by kytrinyx** [comment]
> does this matter to you

I can't decide one way or the other. My instinct says `slug` first, since it's the identifier for the exercise.

Let's take this and change it later if we decide we care enough!

**Comment by petertseng** [comment]
Thanks everyone.

**Pull request merged**
