### PR TITLE
Adding track specific documentation.

### PR DESCRIPTION
**Pull request by vguerra**
Reference : https://github.com/exercism/rossconf/issues/1

### CODE REVIEW

**Comment by vguerra** [comment]
I hate that build passes on my fork :'(

**Comment by kytrinyx** [comment]
Ah, builds in Go are tricky. I wrote a blog post about it. Check if this is relevant: https://splice.com/blog/contributing-open-source-git-repositories-go/

**Comment by kytrinyx** [comment]
I don't think travis is running the build on your fork: https://travis-ci.org/vguerra/xgo

Did you mean that it passes locally?

**Comment by kytrinyx** [comment]
The problem here is that `config.json` doesn't have `docs` in the "ignored" key:

```
$ configlet .
Evaluating .
-> config.json does not include [docs].
```

**Comment by vguerra** [comment]
@kytrinyx true... config.json slipped out of my commit :\ .. now everything is good! :+1:

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
