### PR TITLE
Robot simulator - Update 2

### PR DESCRIPTION
**Pull request by jbsmith7741**
Phase 2 involves changing the global variables X, Y and Facing (Dir) into a named struct. This is mostly to make the step 1 feel more uniform to step 2 and 3

### CODE REVIEW

**Comment by petertseng** [comment]
I think the main change here is to add a `Robot1` surrounding the formerly-global `X, Y`, and `Facing` (`Dir`), right? I would find that valuable.

**Comment by petertseng** [comment]
(also can we get a rebase on master so that we can see what changes we have remaining to deal with? Thanks)

**Comment by petertseng** [comment]
Yeah this is looking good! As soon as you can change the test version of the example I think we will be ready!

**Comment by jbsmith7741** [comment]
Let me know if anything else needs to be changed

**Comment by petertseng** [comment]
Everything is looking good here! Thanks!

**Pull request merged**
