### PR TITLE
Add react exercise

### PR DESCRIPTION
**Pull request by pminten**
See exercism/x-common#83.

### CODE REVIEW

**Comment by kytrinyx** [comment]
The build is failing for Go tip (not 1.3, not 1.4), but I think it is unrelated to this exercise, but rather something that _tournament_ is triggering:

```plain
--- FAIL: TestTallyHappy-2 (0.00s)
	tournament_test.go:124: Tally for input named "ignore empty lines" returned error "line 5, column 0: wrong number of fields in line". Error not expected.
FAIL
FAIL	github.com/exercism/xgo/tournament	0.005s
```

**Comment by pminten** [comment]
Still works with 1.4.2 source release. Maybe it's best to have this PR wait until the next Go release. It could be that this is just a bug in Go tip that we're running into.

**Comment by kytrinyx** [comment]
Yes, it might be a bug. Let's hold off on it for a bit. I'll retrigger the build periodically to see if it passes on a more recent tip.

**Comment by dgryski** [comment]
If it consistently fails against tip it should be trivial to git-bisect to find the offending commit.

**Comment by kytrinyx** [comment]
True! I forgot that go was in git now. Back when it was in hg I treated the history as a bit of a black box since my hg skills are essentially nil.

**Comment by dgryski** [comment]
Bisect says that the first bad commit is https://github.com/golang/go/commit/2db58f8f2daea1c6f6134584f7811bb229177b28 , which given that it's an encoding/csv change and Tally uses encoding/csv is believable.

**Comment by pminten** [comment]
That explains it. The CSV I use has varying number of fields per record. It's a precondition violation on my side that this commit turned into an actual crash.

I'll fix this tomorrow.

Thanks for your help in hunting this down.

Damian Gryski <notifications@github.com> schreef op 6 juni 2015 21:12:37 CEST:
>Bisect says that the first bad commit is
>https://github.com/golang/go/commit/2db58f8f2daea1c6f6134584f7811bb229177b28
>, which given that it's an encoding/csv change and Tally uses
>encoding/csv is believable.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/xgo/pull/170#issuecomment-109638354

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by pminten** [comment]
Ok, I've figured out where exactly things went wrong. The Go code used to accept empty lines because it checks for whether the `fields []string` slice from parseRecord is nil and if so skips that line. The `fields` slice is zero initialized, meaning `nil`. If no fields are appended it stays nil and thus the line is skipped. However the golang/go@2db58f8 commit preallocates the slice so that even if no fields are found the slice is not `nil`. This causes newlines to no longer be skipped.

I'm going to change the tests a bit to require comment lines instead of newlines to be filtered. This still requires a bit of thought on the side of the user but works with the Go CSV reader (since you can specify a comment char). The bump in TestVersion should hopefully prevent people from running into this issue with code that worked for the old Go but not for the new one. Will make a new PR for this, once that's merged this one should be mergeable as well.

**Comment by pminten** [comment]
Update: just noticed Go supports variable number of fields. Still going to bump testVersion and require handling of comments (since that's just one extra field to set for the user) but will leave newline in.

**Comment by kytrinyx** [comment]
The newlines fix is merged into master and I've retriggered the build.

**Comment by kytrinyx** [comment]
And it's good to go. Thanks, everyone for hunting that down!

**Pull request merged**
